### ISSUE TITLE
code for paper

### ISSUE THREAD

**Issue by littlewine** [orionw/NevIR#1]
Hi and thanks for sharing your nice work!

Will the code for the paper be released soon?

**Comment by orionw** [comment]
Hi and thanks for your interest! 

I was planning to do it in the next couple weeks, now that the EACL anonymity deadline is over for some other work I've been doing.  

I can probably upload an evaluation script within a few working days - is there a specific part you're looking for besides that? I can be sure to prioritize whatever you're looking for.

**Comment by orionw** [comment]
I've uploaded the evaluation code, you can choose models to evaluate in `src/negations/evaluate.py` and run using those options. Let me know if that doesn't work or if there's anything else I can help with!

**Comment by littlewine** [comment]
Thanks a lot! I will check it out soon!
